import './globals.css'
import './privacy/privacy.css'

import type { Metadata } from 'next'

//Components
import Navbar from '@/components/layout/Navigation/Navigation'
import ScrollBtn from '@/components/layout/ScrollButton/ScrollButton'
import Footer from '@/components/layout/Footer/Footer'

//fonts
import { Inter,  Special_Elite } from 'next/font/google'
import CookieModal from '@/components/services/Cookie/CookieModal'
const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'ATBS Abkanttechnik Braunschweig - ihre Metallverarbeiter!',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {  
  return (
    <html lang="de">
      <body className={inter.className}>
        <div className="">
          <Navbar />
          {children}
          <CookieModal/>
          <ScrollBtn/>
        </div>
        <Footer />
      </body>
    </html>
  )
}
