import TextImage from "@/components/ux/TextImage/TextImage";
import TextImageReverse from "@/components/ux/TextImageReverse/TextImageReverse";
import { FaArrowDown } from "react-icons/fa";
import './services.css';

export default function Services() {
    return (
    <section className="servicesContainer">
        <div className="pt-16">
            <h2 className="text-2xl sm:text-4xl">Leistungen</h2>
        </div> 
        <p className="pt-11 pl-8 pr-8 text-center">
            Bei ATBS bieten wir eine umfassende Palette an Metallbearbeitungsdiensten an, darunter Schweißen, Laserschneiden, Kanten und Planen. Unser Anspruch ist es, jede Leistung mit höchster Sorgfalt und Präzision auszuführen.
            <br/>
            Dank modernster Automatisierungstechnik und Robotik sind wir in der Lage, auch komplexe Projekte effizient und zuverlässig zu realisieren. Entdecken Sie unsere verschiedenen Dienstleistungen im Detail und erfahren Sie, wie wir Ihre Anforderungen optimal erfüllen können.          
        </p>
        <a href="/services#one" className="md:block hidden  mt-16 mb-8"><button className="text-bg flex flex-row gap-8 items-center"><FaArrowDown className="text-6xl text-bg bg-primary hover:bg-primary2 rounded-full p-4 transition-all duration-300 ease-in-out"/> <h4 className="cursor-pointer">Lies mehr!</h4></button></a>
        <div className="servicesContent" id="one">
            <TextImage heading="Zerspanung" imageSrc="/images/actions/fräsen_1.jpg" imageAlt="Zerspanung" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit." />
            <TextImageReverse heading="Lasertechnik" imageSrc="/images/actions/lasern_1.jpg" imageAlt="Lasertechnik" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit."/>
            <TextImage heading="Kanttechnik" imageSrc="/images/actions/kanten_2.jpg" imageAlt="Kanttechnik" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit." />
            <TextImageReverse heading="Schweisstechnik" imageSrc="/images/actions/schweißen_1.jpg" imageAlt="Schweisstechnik" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit."/>
            <TextImage heading="Oberflächen&shy;behandlung" imageSrc="/images/maschines/oberfläche2.jpg" imageAlt="Oberflaeche" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit." />
            <TextImageReverse heading="Rohrlasertechnik" imageSrc="/images/actions/lasern_3.jpg" imageAlt="Brennschneiden" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit."/>
            <TextImage heading="Baugruppen&shy;fertigung" imageSrc="/images/actions/baugruppe.jpg" imageAlt="Baugruppenfertigung" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit." />
            <TextImageReverse heading="Konstruktion" imageSrc="/images/actions/cad_2.jpg" imageAlt="Konstruktion" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit."/>
            <TextImage heading="Stanztechnik" imageSrc="/images/actions/oberfläche.jpg" imageAlt="Stanztechnik" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Curabitur pretium tincidunt lacus. Nulla gravida orci a odio. Nullam varius, turpis et commodo pharetra, est eros bibendum elit." />
        </div>
    </section>
    );
}